### ISSUE TITLE
FloFaber\MphpD\Queue::get(): Return value must be of type array, bool returned

### ISSUE THREAD

**Issue by tschlaeppi** [FloFaber/MphpD#18]
Queue::get() fails on an empty queue.

shouldn't this line
`public function get($p = -1) : array`

look this way?
`public function get($p = -1) : array|bool`

**Comment by FloFaber** [comment]
Yes. `Queue::get()` should either return `array` or `false` but never `true`. I will fix the return type ASAP.
In the case of an empty queue however it should return an empty `array`. What exactly do you mean by "fails"?

**Comment by tschlaeppi** [comment]
@FloFaber:
I forgot to call MphpD::connect() and the Queue::get() returned false in this case. My bad. Since I connect mpd, i get an empty array, as expected.
Thanks!

**Comment by FloFaber** [comment]
Yes, that would be considered a failure and cause `Queue::get` to return `false`. The return type is now fixed in v1.1.1.
