### ISSUE TITLE
Error reading some directories

### ISSUE THREAD

**Issue by mororc** [FloFaber/MphpD#21]
There is a folder with files

$folder="music/Laïka - Good Looking Blues (2000) [16B-44.1kHz]";
$mphpd->db()->ls($folder); 

return false

other players see it

I suspect there is a problem with the name of the folder itself, in particular the symbol " ï "

rename folder to " music/Laika - Good Looking Blues (2000) [16B-44.1kHz] " returns a successful result

**Comment by FloFaber** [comment]
Thanks for reporting. Will fix it ASAP!

**Comment by FloFaber** [comment]
Unfortunately I'm unable to reproduce the bug. I've created a folder called `Laïka - Good Looking Blues (2000) [16B-44.1kHz]`, updated the DB and called `ls` on the folder. For me it works:
```
$folder = "Laïka - Good Looking Blues (2000) [16B-44.1kHz]";
if(($ls = $mphpd->db()->ls($folder)) === false){
  print_r($mphpd->get_last_error());
  return false;
}
print_r($ls);
```
prints
```
Array
(
    [files] => Array
        (
            [0] => Array
                (
                    [size] => 1800792
                    [last-modified] => 2023-11-22T17:56:50Z
                    [name] => test-song3.mp3
                )
            [1] => Array
                (
                    [size] => 1898739
                    [last-modified] => 2023-02-19T12:17:19Z
                    [name] => test-song2.mp3
                )
            [2] => Array
                (
                    [size] => 1898739
                    [last-modified] => 2023-02-19T12:17:19Z
                    [name] => test-song1.mp3
                )
        )
    [directories] => Array
        (
        )
    [playlists] => Array
        (
        )
)
```

Please send me the output of `print_r($mphpd->get_last_error());` after calling `ls`. Can you see the folder with `$mphpd->db()->ls("music");`?

**Comment by mororc** [comment]
i have error from $mphpd->get_last_error()
{
  "code": 52,
  "message": "Laka - Good Looking Blues (2000) [16B-44.1kHz]/: No such file or directory",
  "command": "listfiles",
  "commandlistnum": 0
}

**Comment by FloFaber** [comment]
I'm still unable to reproduce it. I've tried php's built-in server (`php -S`), apache and nginx. 

_`...Failed to open Laka...`_ seems to me like the special char "ï" is simply removed from the string.
Are all non-ascii characters (ä,ö,ü,...) removed? Which webserver are you using? Is there any difference between `phpinfo()` on cli and `phpinfo()` when using the webserver?

**Comment by mororc** [comment]
commented out the line
MphpD/Utils.php:59
//$param = escapeshellcmd($param);

now works correctly

**Comment by FloFaber** [comment]
Then escapeshellcmd removes special characters. Which locale are you using? `echo setlocale(LC_ALL, 0);`
Try setting it to en_US.UTF-8: `setlocale(LC_ALL, "en_US.UTF-8");`.

**Comment by FloFaber** [comment]
@mororc I can reproduce the issue when I set LC_CTYPE to "C" with `setlocale(LC_CTYPE, "C")`.
If you set it to some available utf-8 locale this issue should be resolved.
